name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Change this if your default branch is different
  pull_request:
    branches: ["main"] # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"] # Specify the Node.js version you want to use

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <suppport+action@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
